# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Question1 = QtWidgets.QPushButton(self.centralwidget)
        self.Question1.setGeometry(QtCore.QRect(90, 180, 121, 41))
        self.Question1.setObjectName("Question1")
        self.Question2 = QtWidgets.QPushButton(self.centralwidget)
        self.Question2.setGeometry(QtCore.QRect(90, 330, 121, 41))
        self.Question2.setObjectName("Question2")
        self.Question3 = QtWidgets.QPushButton(self.centralwidget)
        self.Question3.setGeometry(QtCore.QRect(90, 250, 121, 41))
        self.Question3.setObjectName("Question3")
        self.Question4 = QtWidgets.QPushButton(self.centralwidget)
        self.Question4.setGeometry(QtCore.QRect(90, 400, 121, 41))
        self.Question4.setObjectName("Question4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 291, 81))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Question1.setText(_translate("MainWindow", "第一问"))
        self.Question2.setText(_translate("MainWindow", "第三问"))
        self.Question3.setText(_translate("MainWindow", "第二问"))
        self.Question4.setText(_translate("MainWindow", "第四问"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Python大作业</span></p></body></html>"))
