# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Question3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 551, 71))
        self.label.setObjectName("label")
        self.AnimeRecommendationGraph1 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeRecommendationGraph1.setGeometry(QtCore.QRect(30, 110, 211, 51))
        self.AnimeRecommendationGraph1.setObjectName("AnimeRecommendationGraph1")
        self.AnimeIndexSituation1 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeIndexSituation1.setGeometry(QtCore.QRect(30, 230, 211, 51))
        self.AnimeIndexSituation1.setObjectName("AnimeIndexSituation1")
        self.AnimeSituation1 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeSituation1.setGeometry(QtCore.QRect(30, 350, 211, 51))
        self.AnimeSituation1.setObjectName("AnimeSituation1")
        self.AnimeRecommendationGraph2 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeRecommendationGraph2.setGeometry(QtCore.QRect(30, 170, 211, 51))
        self.AnimeRecommendationGraph2.setObjectName("AnimeRecommendationGraph2")
        self.AnimeCommentSituation1 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeCommentSituation1.setGeometry(QtCore.QRect(250, 350, 71, 51))
        self.AnimeCommentSituation1.setObjectName("AnimeCommentSituation1")
        self.AnimeIndexDict1 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeIndexDict1.setGeometry(QtCore.QRect(250, 230, 71, 51))
        self.AnimeIndexDict1.setObjectName("AnimeIndexDict1")
        self.AnimeRecommendationExcel2 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeRecommendationExcel2.setGeometry(QtCore.QRect(250, 170, 71, 51))
        self.AnimeRecommendationExcel2.setObjectName("AnimeRecommendationExcel2")
        self.AnimeRecommendationExcel1 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeRecommendationExcel1.setGeometry(QtCore.QRect(250, 110, 71, 51))
        self.AnimeRecommendationExcel1.setObjectName("AnimeRecommendationExcel1")
        self.AnimeIndexSituation2 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeIndexSituation2.setGeometry(QtCore.QRect(30, 290, 211, 51))
        self.AnimeIndexSituation2.setObjectName("AnimeIndexSituation2")
        self.AnimeIndexDict2 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeIndexDict2.setGeometry(QtCore.QRect(250, 290, 71, 51))
        self.AnimeIndexDict2.setObjectName("AnimeIndexDict2")
        self.AnimeCommentSituation2 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeCommentSituation2.setGeometry(QtCore.QRect(250, 410, 71, 51))
        self.AnimeCommentSituation2.setObjectName("AnimeCommentSituation2")
        self.AnimeSituation2 = QtWidgets.QPushButton(self.centralwidget)
        self.AnimeSituation2.setGeometry(QtCore.QRect(30, 410, 211, 51))
        self.AnimeSituation2.setObjectName("AnimeSituation2")
        self.Comparison = QtWidgets.QPushButton(self.centralwidget)
        self.Comparison.setGeometry(QtCore.QRect(30, 480, 291, 51))
        self.Comparison.setObjectName("Comparison")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'楷体\'; font-size:14pt;\">第三题：根据一部动画片，分析与其最相似的动画片</span></p></body></html>"))
        self.AnimeRecommendationGraph1.setText(_translate("MainWindow", "看过CLAS还推荐的动画"))
        self.AnimeIndexSituation1.setText(_translate("MainWindow", "根据CLAS标签的推荐情况"))
        self.AnimeSituation1.setText(_translate("MainWindow", "根据CLAS评论的推荐情况"))
        self.AnimeRecommendationGraph2.setText(_translate("MainWindow", "看过摇曳露营还推荐的动画"))
        self.AnimeCommentSituation1.setText(_translate("MainWindow", "对应数据"))
        self.AnimeIndexDict1.setText(_translate("MainWindow", "对应数据"))
        self.AnimeRecommendationExcel2.setText(_translate("MainWindow", "对应数据"))
        self.AnimeRecommendationExcel1.setText(_translate("MainWindow", "对应数据"))
        self.AnimeIndexSituation2.setText(_translate("MainWindow", "根据摇曳露营标签的推荐情况"))
        self.AnimeIndexDict2.setText(_translate("MainWindow", "对应数据"))
        self.AnimeCommentSituation2.setText(_translate("MainWindow", "对应数据"))
        self.AnimeSituation2.setText(_translate("MainWindow", "根据摇曳露营评论的推荐情况"))
        self.Comparison.setText(_translate("MainWindow", "摇曳露营与CLAS两部动画的推荐比较"))
