# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Question1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 401, 91))
        self.label.setObjectName("label")
        self.KindCompare1 = QtWidgets.QPushButton(self.centralwidget)
        self.KindCompare1.setGeometry(QtCore.QRect(60, 130, 281, 61))
        self.KindCompare1.setObjectName("KindCompare1")
        self.KindCompare2 = QtWidgets.QPushButton(self.centralwidget)
        self.KindCompare2.setGeometry(QtCore.QRect(60, 210, 281, 61))
        self.KindCompare2.setObjectName("KindCompare2")
        self.PeriodCompare1 = QtWidgets.QPushButton(self.centralwidget)
        self.PeriodCompare1.setGeometry(QtCore.QRect(60, 290, 281, 61))
        self.PeriodCompare1.setObjectName("PeriodCompare1")
        self.PeriodCompare2 = QtWidgets.QPushButton(self.centralwidget)
        self.PeriodCompare2.setGeometry(QtCore.QRect(60, 370, 281, 61))
        self.PeriodCompare2.setObjectName("PeriodCompare2")
        self.PeriodCompare3 = QtWidgets.QPushButton(self.centralwidget)
        self.PeriodCompare3.setGeometry(QtCore.QRect(60, 450, 281, 61))
        self.PeriodCompare3.setObjectName("PeriodCompare3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 130, 91, 61))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'楷体\'; font-size:14pt;\">第一题：动画片在近年来的发展现状</span></p></body></html>"))
        self.KindCompare1.setText(_translate("MainWindow", "bangumi动画排行榜前100页中\n"
"TV动画与OVA/剧场版比例"))
        self.KindCompare2.setText(_translate("MainWindow", "bangumi动画排行榜前100页\n"
"的TV动画中篇幅所占比例"))
        self.PeriodCompare1.setText(_translate("MainWindow", "bangumi动画排行榜前100页的动画\n"
"在五个年代段的评分及数量情况"))
        self.PeriodCompare2.setText(_translate("MainWindow", "bangumi动画排行榜前100页的动画在\n"
"2011-2021年间分布的评分及数量情况"))
        self.PeriodCompare3.setText(_translate("MainWindow", "bangumi动画排行榜前100页的动画\n"
"的评分人数在2011-2021年间的分布"))
        self.pushButton.setText(_translate("MainWindow", "排行榜表格"))
