# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Searching1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(960, 600)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 170, 301, 71))
        self.label.setObjectName("label")
        self.ChosenBox = QtWidgets.QComboBox(Dialog)
        self.ChosenBox.setGeometry(QtCore.QRect(350, 150, 561, 61))
        self.ChosenBox.setObjectName("ChosenBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 440, 431, 121))
        self.label_2.setObjectName("label_2")
        self.Okbutton = QtWidgets.QPushButton(Dialog)
        self.Okbutton.setGeometry(QtCore.QRect(700, 490, 111, 31))
        self.Okbutton.setObjectName("Okbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">请选择你要查找的动画名称：</span></p><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">注：若未找到需要更换动画的名称再试</span></p><p><span style=\" font-size:12pt;\">建议使用标准名称进行搜索，</span><span style=\" font-size:12pt;\">不要使用别名</span></p></body></html>"))
        self.Okbutton.setText(_translate("Dialog", "确定"))
